import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix='+', intents=intents)

@bot.event
async def on_ready():
    print(f'Conectado como {bot.user} (ID: {bot.user.id})')
    print('------')

objetos_reciclables = ['Lista de objetos reciclables:','Papel', 'Cartón', 'Vidrio', 'Plástico', 'Metal', 'Aluminio', 'Textil', 'Electrónico', 'Orgánico', 'Madera', 'Neumáticos', 'Baterías', 'Envases', 'Botellas', 'Latas', 'Tetra_pack', 'Periódicos', 'Revistas', 'Cartuchos', 'Tubos']

ob = {
    'Papel': 'El papel es una fuente importante de deforestación y contribuye a la contaminación del agua y el aire debido a los procesos de fabricación. Afortunadamente, su tiempo de descomposición es relativamente corto, de 2 a 5 meses. Reciclar papel implica su reutilización para hacer papel reciclado, cartón corrugado y empaques, reduciendo así la necesidad de talar árboles.',
    'Cartón': 'Los problemas asociados con el cartón incluyen la generación de desechos voluminosos en vertederos. Aunque el cartón puede descomponerse en 1 a 5 meses, su reciclaje es vital. El cartón reciclado se utiliza para producir papel reciclado, envases y materiales de embalaje, lo que ayuda a reducir la necesidad de materiales nuevos.',
    'Vidrio': 'A pesar de que el vidrio es inerte y no se descompone, su acumulación en vertederos y la contaminación del suelo son problemas importantes. Reciclar vidrio es esencial, ya que puede ser reciclado infinitamente. El vidrio reciclado se utiliza para fabricar nuevos envases de vidrio, botellas y frascos, contribuyendo así a la conservación de recursos naturales.',
    'Plástico': 'El plástico es uno de los mayores problemas ambientales debido a su contaminación marina, la acumulación en vertederos y las emisiones de gases de efecto invernadero durante su producción. Aunque algunos plásticos pueden tardar siglos en descomponerse, reciclarlos es crucial. El plástico reciclado se utiliza para fabricar una variedad de productos, como botellas, contenedores y bolsas, reduciendo así la demanda de plásticos nuevos. El tiempo de descomposición varía según el tipo de plástico, pero puede ser de cientos a miles de años.',
    'Metal': 'La contaminación del suelo y el agua, junto con las emisiones de gases durante la extracción y procesamiento, son problemas asociados con los metales. Aunque los metales no se descomponen, su reciclaje es fundamental para conservar recursos naturales. El metal reciclado se utiliza para producir latas, utensilios de cocina, herramientas y otros productos metálicos, ayudando así a reducir la necesidad de extracción de minerales. El tiempo de descomposición de los metales es indefinido, ya que no se descomponen en condiciones naturales.',
    'Aluminio': 'A pesar de ser infinitamente reciclable, el aluminio causa problemas ambientales debido a la contaminación del aire y del agua, y al agotamiento de recursos naturales durante su producción. Reciclar aluminio es esencial para reducir estos impactos. El aluminio reciclado se utiliza para fabricar nuevas latas de aluminio, piezas de automóviles y componentes electrónicos, lo que ayuda a conservar recursos y energía. El tiempo de descomposición del aluminio es indefinido, ya que es un metal y no se descompone en condiciones naturales.',
    'Textil': 'La industria textil contribuye a la contaminación química y al agotamiento de recursos hídricos, además de generar desechos textiles en vertederos. Aunque el tiempo de descomposición de los textiles varía, desde meses hasta siglos, reciclar textiles es importante. Los textiles reciclados se pueden reutilizar en la fabricación de nuevos productos textiles, convertirse en fibras mediante reciclaje mecánico o utilizarse en la fabricación de aislamientos, contribuyendo así a reducir el impacto ambiental de la industria textil.',
    'Electrónico': 'La acumulación de desechos electrónicos y la contaminación por metales pesados son problemas ambientales asociados con los dispositivos electrónicos. Aunque los componentes electrónicos pueden tardar cientos de años en descomponerse, su reciclaje es esencial. Los componentes electrónicos reciclados se utilizan para recuperar metales preciosos y materiales valiosos, y para reacondicionar y reutilizar dispositivos, lo que ayuda a reducir la demanda de recursos y la generación de desechos electrónicos. El tiempo de descomposición de los materiales electrónicos es indefinido, ya que no se descomponen en condiciones naturales.',
    'Orgánico': 'Los problemas asociados con los residuos orgánicos incluyen la generación de gases de efecto invernadero en vertederos y la contaminación del agua. Aunque el tiempo de descomposición de los materiales orgánicos varía, desde semanas hasta años, reciclarlos es esencial. El compostaje de residuos orgánicos produce abono orgánico y biogás para energía, reduciendo así la cantidad de residuos orgánicos en vertederos y las emisiones de gases de efecto invernadero.',
    'Madera': 'La deforestación y la contaminación del suelo son problemas ambientales asociados con la madera. Aunque la madera puede tardar años o décadas en descomponerse, su reciclaje es importante. La madera reciclada se utiliza para fabricar muebles, papel reciclado, biomasa para energía y otros productos, lo que ayuda a reducir la necesidad de talar árboles y a conservar recursos naturales. El tiempo de descomposición de la madera varía según el tipo de madera y las condiciones ambientales.',
    'Neumáticos': 'La acumulación de desechos de neumáticos en vertederos y los riesgos de incendio son problemas ambientales importantes. Aunque los neumáticos pueden tardar siglos en descomponerse, su reciclaje es crucial. Los neumáticos reciclados se utilizan para producir nuevos productos de caucho, asfalto modificado y relleno para campos deportivos, lo que ayuda a reducir la cantidad de neumáticos desechados y los impactos ambientales asociados. El tiempo de descomposición de los neumáticos es largo y puede ser de cientos de años.',
    'Baterías': 'La contaminación del suelo y del agua por metales pesados como el plomo y el mercurio es un problema ambiental significativo asociado con las baterías. Aunque las baterías no se descomponen, su reciclaje es esencial para evitar la liberación de toxinas. Las baterías recicladas se utilizan para recuperar metales preciosos y materiales valiosos, y para reutilizar materiales en nuevas baterías, lo que ayuda a reducir la demanda de recursos naturales y la generación de desechos peligrosos. El tiempo de descomposición de las baterías es indefinido, ya que no se descomponen en condiciones naturales.',
    'Envases': 'La acumulación de envases en vertederos y la contaminación del suelo y del agua son problemas ambientales asociados con los envases. Aunque el tiempo de descomposición de los envases depende del material, reciclarlos es fundamental. Los envases reciclados se utilizan para producir nuevos envases, materiales de embalaje y otros productos, lo que ayuda a reducir la cantidad de desechos y conservar recursos naturales.',
    'Botellas': 'Las botellas contribuyen a la contaminación marina y la acumulación en vertederos. El tiempo de descomposición de las botellas depende del material del que están hechas. Reciclar botellas es esencial para reducir su impacto ambiental. Las botellas recicladas se utilizan para fabricar nuevas botellas, envases, fibras textiles y otros productos, ayudando así a conservar recursos y reducir la cantidad de desechos plásticos.',
    'Latas': 'Las latas pueden causar contaminación del suelo y del agua, así como acumulación en vertederos. El tiempo de descomposición de las latas depende del material del que están hechas. Reciclar latas es importante para conservar recursos naturales y reducir la cantidad de desechos metálicos. Las latas recicladas se utilizan para fabricar nuevas latas, utensilios de cocina, herramientas y otros productos metálicos, contribuyendo así a la sostenibilidad ambiental.',
    'Tetra_pack': 'Los envases tipo Tetra Pack pueden contribuir a la acumulación de desechos en vertederos y la contaminación del suelo y del agua. El tiempo de descomposición de estos envases depende de los materiales utilizados en su fabricación. Reciclar los envases Tetra Pack es importante para reducir su impacto ambiental. Los envases Tetra Pack reciclados se utilizan para producir nuevos envases, materiales de embalaje y otros productos, ayudando así a conservar recursos naturales y reducir la cantidad de desechos plásticos.',
    'Periódicos': 'Los periódicos contribuyen a la deforestación y la contaminación del agua y del aire debido a los procesos de fabricación. El tiempo de descomposición de estos materiales depende de varios factores, incluida la composición del papel y las condiciones ambientales. Reciclar periódicos y revistas es importante para reducir la necesidad de talar árboles y conservar recursos naturales. El papel reciclado se utiliza para producir nuevos periódicos, revistas, papel de embalaje y otros productos, contribuyendo así a la sostenibilidad ambiental.',
    'Revistas': 'Las revistas contribuyen a la deforestación y la contaminación del agua y del aire debido a los procesos de fabricación. El tiempo de descomposición de estos materiales depende de varios factores, incluida la composición del papel y las condiciones ambientales. Reciclar periódicos y revistas es importante para reducir la necesidad de talar árboles y conservar recursos naturales. El papel reciclado se utiliza para producir nuevos periódicos, revistas, papel de embalaje y otros productos, contribuyendo así a la sostenibilidad ambiental.',
    'Cartuchos': 'Los cartuchos de impresora pueden contribuir a la generación de desechos electrónicos y la contaminación por metales pesados. El tiempo de descomposición de los cartuchos depende de los materiales utilizados en su fabricación y puede ser significativo. Reciclar cartuchos es esencial para reducir su impacto ambiental y conservar recursos naturales. Los cartuchos reciclados se pueden reacondicionar y reutilizar, o desmontar para recuperar materiales valiosos, como plásticos y metales, contribuyendo así a la reducción de la generación de desechos electrónicos y la conservación de recursos.',
    'Tubos': 'Los tubos de diversos materiales pueden contribuir a la acumulación de desechos en vertederos y la contaminación del suelo y del agua. El tiempo de descomposición de los tubos depende del material del que están hechos. Reciclar tubos es importante para reducir su impacto ambiental y conservar recursos naturales. Los tubos reciclados se pueden reutilizar en la fabricación de nuevos productos, o desmontar para recuperar materiales valiosos, contribuyendo así a la sostenibilidad ambiental.'
}
@bot.command()
async def lis(ctx):
    for objeto in objetos_reciclables:
        await ctx.send(objeto)

@bot.command()
async def info(ctx,material: str):
    if material in ob:
        await ctx.send(f'{material.title()} \n {ob[material]}')
        file_name = f'recy/{material.lower()}.jpg' 
        with open(file_name, 'rb') as f:
                picture = discord.File(f)
                await ctx.send(file=picture)    
    else:
        await ctx.send("Lo siento, no tengo información sobre el tiempo de descomposición de ese material.")

bot.run('token')
